name: 🔨 Performance Test

on:
  workflow_dispatch:
  schedule:
    # Weekly
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Test Performance
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    if: github.repository == 'projectdiscovery/nuclei'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: projectdiscovery/actions/setup/go@v1

      - name: Verify Go modules
        run: make verify

      # Max GH exection time 6H => timeout after that
      - name: Running performance with big list
        run: go run -race . -l ../functional-test/targets-150.txt
        working-directory: cmd/nuclei/